# Generated by Django 5.0.7 on 2024-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line_1',
            field=models.CharField(default='Not Provided', max_length=255, verbose_name='Address Line 1'),
        ),
        migrations.AddField(
            model_name='organization',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AddField(
            model_name='organization',
            name='city',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='organization',
            name='country',
            field=models.CharField(choices=[('IN', 'India')], default='IN', max_length=2, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(default='Unnamed Organization', max_length=255, verbose_name='Organization Name'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_photo',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/photos/', verbose_name='Organization Photo or Logo'),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=20, verbose_name='Phone'),
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('AN', 'Andaman and Nicobar Islands'), ('AP', 'Andhra Pradesh'), ('AR', 'Arunachal Pradesh'), ('AS', 'Assam'), ('BR', 'Bihar'), ('CH', 'Chandigarh'), ('CT', 'Chhattisgarh'), ('DD', 'Dadra and Nagar Haveli and Daman and Diu'), ('DL', 'Delhi'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('HP', 'Himachal Pradesh'), ('HR', 'Haryana'), ('JH', 'Jharkhand'), ('JK', 'Jammu and Kashmir'), ('KA', 'Karnataka'), ('KL', 'Kerala'), ('LA', 'Ladakh'), ('LD', 'Lakshadweep'), ('MH', 'Maharashtra'), ('MN', 'Manipur'), ('ML', 'Meghalaya'), ('MZ', 'Mizoram'), ('NL', 'Nagaland'), ('OD', 'Odisha'), ('PY', 'Puducherry'), ('PB', 'Punjab'), ('RJ', 'Rajasthan'), ('SK', 'Sikkim'), ('TN', 'Tamil Nadu'), ('TS', 'Telangana'), ('TR', 'Tripura'), ('UP', 'Uttar Pradesh'), ('UT', 'Uttarakhand'), ('WB', 'West Bengal')], default='JH', max_length=2, verbose_name='State'),
        ),
        migrations.AddField(
            model_name='organization',
            name='twitter_url',
            field=models.URLField(blank=True, null=True, verbose_name='Twitter URL'),
        ),
        migrations.AddField(
            model_name='organization',
            name='website',
            field=models.URLField(default='a.com', verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='organization',
            name='zip_code',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
