# Generated by Django 5.0.7 on 2024-08-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0006_alter_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='country',
            field=models.CharField(blank=True, choices=[('IN', 'India')], max_length=2, null=True, verbose_name='Country'),
        ),
    ]
