# Generated by Django 5.0.7 on 2024-08-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0008_volunteeropportunity_address_line_1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeropportunity',
            old_name='address_line_2',
            new_name='cause_areas',
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='requirement',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
