# Generated by Django 5.0.7 on 2024-08-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0009_rename_address_line_2_volunteeropportunity_cause_areas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='about',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='address_line_2',
        ),
        migrations.AddField(
            model_name='organization',
            name='mission_satement',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Mission Statement'),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Organization Description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_photo',
            field=models.URLField(blank=True, null=True, verbose_name='organization_photo'),
        ),
    ]
