# Generated by Django 5.0.7 on 2024-08-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0012_rename_mission_satement_organization_mission_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mission Statement'),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='title',
            field=models.TextField(blank=True, null=True, verbose_name='title'),
        ),
    ]
